### ISSUE TITLE
proxyTable无效

### ISSUE THREAD

**Issue by zhanghao123** [cccyb/vue-zhihu-daily#1]
运行npm run dev时，报错：
[HPM] Error occurred while trying to proxy request /news/latest from localhost:9000 to http://news-at.zhihu.com/api/4 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /themes from localhost:9000 to http://news-at.zhihu.com/api/4 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
请问知道是什么原因么

**Comment by cccyb** [comment]
我这里没出现这个问题，你可以试试以下解决方法：
- 重新安装全部依赖
- 可以试着**升级**一下`http-proxy-middleware`这个依赖的
- 在`config/index.js`文件给proxyTable的每一项添加`"secure": false`参数

**Comment by kangzhongyao** [comment]
npm run dev 无法运行，报错如下
Uncaught Error: Module build failed: ModuleBuildError: Module build failed: Error: Missing binding F:\zhihu\vue-zhihu-daily\node_modules\.4.5.3@node-sass\vendor\win32-x64-51\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 7.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (F:\zhihu\vue-zhihu-daily\node_modules\.4.5.3@node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\zhihu\vue-zhihu-daily\node_modules\.4.5.3@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\zhihu\vue-zhihu-daily\node_modules\.6.0.5@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at runLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModule.js:192:19)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:364:11
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\Compilation.js:146:10)
    at moduleFactory.create (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\Compilation.js:433:9)
    at factory (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModuleFactory.js:99:14)
    at F:\zhihu\vue-zhihu-daily\node_modules\.0.2.6@tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\CompatibilityPlugin.js:52:5)
    at module.exports (F:\zhihu\vue-zhihu-daily\node_modules\.4.5.3@node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\zhihu\vue-zhihu-daily\node_modules\.4.5.3@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\zhihu\vue-zhihu-daily\node_modules\.6.0.5@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at runLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModule.js:192:19)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:364:11
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (F:\zhihu\vue-zhihu-daily\node_modules\.2.3.0@loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\Compilation.js:146:10)
    at moduleFactory.create (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\Compilation.js:433:9)
    at factory (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\NormalModuleFactory.js:99:14)
    at F:\zhihu\vue-zhihu-daily\node_modules\.0.2.6@tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (F:\zhihu\vue-zhihu-daily\node_modules\.2.6.1@webpack\lib\CompatibilityPlugin.js:52:5)
    at Object.<anonymous> (file:///F:/zhihu/vue-zhihu-daily/dist/static/js/app.bfcb2bea7c9770c96cf7.js:1:74332)
